/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.tafuta.android.app;

public final class R {
    public static final class anim {
        public static final int disappear=0x7f040000;
        public static final int grow_from_bottom=0x7f040001;
        public static final int grow_from_bottomleft_to_topright=0x7f040002;
        public static final int grow_from_bottomright_to_topleft=0x7f040003;
        public static final int grow_from_top=0x7f040004;
        public static final int grow_from_topleft_to_bottomright=0x7f040005;
        public static final int grow_from_topright_to_bottomleft=0x7f040006;
        public static final int pump_bottom=0x7f040007;
        public static final int pump_top=0x7f040008;
        public static final int rail=0x7f040009;
        public static final int shrink_from_bottom=0x7f04000a;
        public static final int shrink_from_bottomleft_to_topright=0x7f04000b;
        public static final int shrink_from_bottomright_to_topleft=0x7f04000c;
        public static final int shrink_from_top=0x7f04000d;
        public static final int shrink_from_topleft_to_bottomright=0x7f04000e;
        public static final int shrink_from_topright_to_bottomleft=0x7f04000f;
    }
    public static final class array {
        public static final int type=0x7f060002;
        public static final int updateIndex=0x7f060001;
        public static final int updateOptions=0x7f060000;
    }
    public static final class attr {
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int columns=0x7f010000;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int dividerColor=0x7f010007;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int endHour=0x7f010009;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int headerWidth=0x7f010001;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int horizontalDivider=0x7f010003;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int hourHeight=0x7f010002;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int labelColor=0x7f010006;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int labelPaddingLeft=0x7f010005;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int labelTextSize=0x7f010004;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int startHour=0x7f010008;
    }
    public static final class color {
        public static final int background1=0x7f070005;
        public static final int background2=0x7f070006;
        public static final int background3=0x7f070007;
        public static final int foreground1=0x7f070003;
        public static final int foreground2=0x7f070004;
        public static final int icon_title=0x7f070009;
        public static final int title_background=0x7f070000;
        public static final int title_separator=0x7f070008;
        public static final int title_text=0x7f070001;
        public static final int title_text_alt=0x7f070002;
    }
    public static final class dimen {
        public static final int actionbar_button_height=0x7f080006;
        public static final int bottom_actionbar_height=0x7f080004;
        public static final int text_size_large=0x7f080003;
        public static final int text_size_medium=0x7f080002;
        public static final int text_size_small=0x7f080001;
        public static final int title_height=0x7f080000;
        public static final int top_padding=0x7f080005;
    }
    public static final class drawable {
        public static final int about=0x7f020000;
        public static final int about_selected=0x7f020001;
        public static final int about_unselected=0x7f020002;
        public static final int action_item_btn=0x7f020003;
        public static final int action_item_selected=0x7f020004;
        public static final int arrow_down=0x7f020005;
        public static final int arrow_up=0x7f020006;
        public static final int balloon_disclosure=0x7f020007;
        public static final int balloon_overlay_bg_selector=0x7f020008;
        public static final int balloon_overlay_close=0x7f020009;
        public static final int balloon_overlay_focused=0x7f02000a;
        public static final int balloon_overlay_unfocused=0x7f02000b;
        public static final int bg=0x7f02000c;
        public static final int blue=0x7f02000d;
        public static final int btn_bg_pressed=0x7f02000e;
        public static final int btn_bg_selected=0x7f02000f;
        public static final int close=0x7f020010;
        public static final int facebook=0x7f020011;
        public static final int facebook_icon=0x7f020012;
        public static final int ic_launcher=0x7f020013;
        public static final int ic_menu_settings=0x7f020014;
        public static final int icon=0x7f020015;
        public static final int icon_launcher=0x7f020016;
        public static final int phone=0x7f020017;
        public static final int popup=0x7f020018;
        public static final int quickcontact_arrow_down=0x7f020019;
        public static final int quickcontact_arrow_up=0x7f02001a;
        public static final int quickcontact_bottom_frame=0x7f02001b;
        public static final int quickcontact_disambig_bottom_bg=0x7f02001c;
        public static final int quickcontact_disambig_divider=0x7f02001d;
        public static final int quickcontact_drop_shadow=0x7f02001e;
        public static final int quickcontact_photo_frame=0x7f02001f;
        public static final int quickcontact_slider_background=0x7f020020;
        public static final int quickcontact_slider_btn=0x7f020021;
        public static final int quickcontact_slider_btn_normal=0x7f020022;
        public static final int quickcontact_slider_btn_on=0x7f020023;
        public static final int quickcontact_slider_btn_pressed=0x7f020024;
        public static final int quickcontact_slider_btn_selected=0x7f020025;
        public static final int quickcontact_slider_grip_left=0x7f020026;
        public static final int quickcontact_slider_grip_right=0x7f020027;
        public static final int quickcontact_top_frame=0x7f020028;
        public static final int red=0x7f020029;
        public static final int search_focused=0x7f02002a;
        public static final int search_unfocused=0x7f02002b;
        public static final int settings_selected=0x7f02002c;
        public static final int settings_unselected=0x7f02002d;
        public static final int share=0x7f02002e;
        public static final int share_icon=0x7f02002f;
        public static final int sms=0x7f020030;
        public static final int submit_id_selected=0x7f020031;
        public static final int submit_id_unselected=0x7f020032;
        public static final int sym_action_add=0x7f020033;
        public static final int sym_action_map=0x7f020034;
        public static final int title_about=0x7f020035;
        public static final int title_color=0x7f02003c;
        public static final int title_pic=0x7f020036;
        public static final int title_search=0x7f020037;
        public static final int title_settings=0x7f020038;
        public static final int title_submit=0x7f020039;
        public static final int twittericon=0x7f02003a;
        public static final int white_color=0x7f02003b;
    }
    public static final class id {
        public static final int AboutTextView=0x7f09000c;
        public static final int arrow_down=0x7f090020;
        public static final int arrow_up=0x7f09001f;
        public static final int balloon_close=0x7f09000a;
        public static final int balloon_inner_layout=0x7f090009;
        public static final int balloon_item_snippet=0x7f090015;
        public static final int balloon_item_title=0x7f090014;
        public static final int balloon_main_layout=0x7f090013;
        public static final int blocks_now=0x7f090008;
        public static final int blocks_ruler=0x7f090007;
        public static final int bottom_actionbar_container=0x7f090004;
        public static final int contact=0x7f09001b;
        public static final int db1_root=0x7f09001c;
        public static final int dialog_discard_confirm=0x7f090003;
        public static final int dialog_moderator=0x7f090005;
        public static final int dialog_wave=0x7f090006;
        public static final int edtext_firstname=0x7f090028;
        public static final int edtext_idnumber=0x7f09002e;
        public static final int edtext_lastname=0x7f09002c;
        public static final int edtext_middlename=0x7f09002a;
        public static final int edtext_phonenumber=0x7f090030;
        public static final int firstname=0x7f090016;
        public static final int footer=0x7f090023;
        public static final int header2=0x7f090021;
        public static final int icon=0x7f09000f;
        public static final int id_number=0x7f090019;
        public static final int idnumber=0x7f090033;
        public static final int imageView1=0x7f09000b;
        public static final int iv_icon=0x7f090011;
        public static final int lastname=0x7f090018;
        public static final int latlon=0x7f090031;
        public static final int lbl_firstname=0x7f090027;
        public static final int lbl_idnumber=0x7f09002d;
        public static final int lbl_lastname=0x7f09002b;
        public static final int lbl_middlename=0x7f090029;
        public static final int lbl_phonenumber=0x7f09002f;
        public static final int lbl_title=0x7f090026;
        public static final int mapview=0x7f09001a;
        public static final int middlename=0x7f090017;
        public static final int relativeLayout1=0x7f09000d;
        public static final int scroll=0x7f090022;
        public static final int scroller=0x7f09001d;
        public static final int search=0x7f090034;
        public static final int send=0x7f090025;
        public static final int send_progress=0x7f090037;
        public static final int share=0x7f09000e;
        public static final int socfb=0x7f090036;
        public static final int soctw=0x7f090035;
        public static final int spn=0x7f090032;
        public static final int submit=0x7f090038;
        public static final int title=0x7f090010;
        public static final int title_container=0x7f090000;
        public static final int title_logo=0x7f090001;
        public static final int title_text=0x7f090002;
        public static final int top=0x7f090024;
        public static final int tracks=0x7f09001e;
        public static final int tv_title=0x7f090012;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int action_item=0x7f030001;
        public static final int action_item_horizontal=0x7f030002;
        public static final int action_item_vertical=0x7f030003;
        public static final int balloon_overlay=0x7f030004;
        public static final int custom_balloon_overlay=0x7f030005;
        public static final int display_id=0x7f030006;
        public static final int horiz_separator=0x7f030007;
        public static final int main=0x7f030008;
        public static final int popup_horizontal=0x7f030009;
        public static final int popup_vertical=0x7f03000a;
        public static final int quickaction=0x7f03000b;
        public static final int search_appeal=0x7f03000c;
        public static final int search_id=0x7f03000d;
        public static final int settings=0x7f03000e;
        public static final int social_media=0x7f03000f;
        public static final int submit_found=0x7f030010;
        public static final int submit_id=0x7f030011;
    }
    public static final class raw {
        public static final int pling=0x7f050000;
    }
    public static final class string {
        /**  About Alert Dialog 
         */
        public static final int about_dialog=0x7f0a002a;
        public static final int about_text=0x7f0a002b;
        public static final int about_us=0x7f0a000d;
        public static final int alert1=0x7f0a0027;
        /**  Application Name 
         */
        public static final int app_name=0x7f0a0000;
        public static final int cancel=0x7f0a0014;
        /**  Alert Dialogs 
         */
        public static final int confirm_listing=0x7f0a0025;
        public static final int confirm_posting=0x7f0a0026;
        public static final int description_about=0x7f0a0003;
        public static final int description_display_id=0x7f0a0006;
        /**  Description UI
         */
        public static final int description_logo=0x7f0a0002;
        public static final int description_search=0x7f0a0008;
        public static final int description_search_appeal=0x7f0a0005;
        public static final int description_settings=0x7f0a0004;
        public static final int description_social=0x7f0a0009;
        public static final int description_submit=0x7f0a0007;
        /**  Display ID 
         */
        public static final int display=0x7f0a0010;
        /**  SubmitID 
         */
        public static final int empty_firstname=0x7f0a0015;
        public static final int empty_idnumber=0x7f0a0018;
        public static final int empty_lastname=0x7f0a0017;
        public static final int empty_middlename=0x7f0a0016;
        public static final int empty_phonenumber=0x7f0a0019;
        public static final int empty_type=0x7f0a001a;
        /**  Maping stuff 
         */
        public static final int enable_gps_network=0x7f0a0011;
        public static final int enable_message=0x7f0a0012;
        /**  maps key
         */
        public static final int google_maps_api_key=0x7f0a0001;
        public static final int gpsPrefs_summary=0x7f0a001e;
        /**  Settings Menu
         */
        public static final int gpsPrefs_title=0x7f0a001d;
        /**  GPS Error Prompt 
         */
        public static final int location_not_found=0x7f0a001c;
        public static final int phonePrefs_summary=0x7f0a0020;
        public static final int phonePrefs_title=0x7f0a001f;
        public static final int search_id=0x7f0a000b;
        public static final int settings=0x7f0a000c;
        public static final int settings_btn=0x7f0a0013;
        public static final int short_phonenumber=0x7f0a001b;
        public static final int smsPrefs_summary=0x7f0a0024;
        public static final int smsPrefs_title=0x7f0a0023;
        public static final int social_media=0x7f0a000e;
        /**  Spinner 
         */
        public static final int spn_id_prompt=0x7f0a000f;
        public static final int status_no=0x7f0a0029;
        public static final int status_yes=0x7f0a0028;
        /**  Bottom UI Buttons 
         */
        public static final int submit_id=0x7f0a000a;
        public static final int userPrefs_summary=0x7f0a0022;
        public static final int userPrefs_title=0x7f0a0021;
    }
    public static final class style {
        public static final int ActionBarSeparator=0x7f0b000c;
        public static final int Animations=0x7f0b0000;
        /**  PopDownMenu 
         */
        public static final int Animations_PopDownMenu=0x7f0b0001;
        public static final int Animations_PopDownMenu_Center=0x7f0b0002;
        public static final int Animations_PopDownMenu_Left=0x7f0b0003;
        public static final int Animations_PopDownMenu_Reflect=0x7f0b0005;
        public static final int Animations_PopDownMenu_Right=0x7f0b0004;
        /**  PopUpMenu 
         */
        public static final int Animations_PopUpMenu=0x7f0b0006;
        public static final int Animations_PopUpMenu_Center=0x7f0b0007;
        public static final int Animations_PopUpMenu_Left=0x7f0b0008;
        public static final int Animations_PopUpMenu_Reflect=0x7f0b000a;
        public static final int Animations_PopUpMenu_Right=0x7f0b0009;
        public static final int BottomActionBarContainer=0x7f0b000d;
        public static final int BottomActionbarButton=0x7f0b000e;
        /**  Formulating the GUI 
         */
        public static final int Theme_D1=0x7f0b000b;
        public static final int TitleBar=0x7f0b000f;
        public static final int TitleBarAction=0x7f0b0013;
        public static final int TitleBarLogo=0x7f0b0010;
        /**  Send Button 
         */
        public static final int TitleBarProgressIndicator=0x7f0b0014;
        public static final int TitleBarSeparator=0x7f0b0011;
        public static final int TitleBarText=0x7f0b0012;
    }
    public static final class styleable {
        /** Attributes that can be used with a BlocksLayout.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #BlocksLayout_columns com.tafuta.android.app:columns}</code></td><td></td></tr>
           </table>
           @see #BlocksLayout_columns
         */
        public static final int[] BlocksLayout = {
            0x7f010000
        };
        /**
          <p>This symbol is the offset where the {@link com.tafuta.android.app.R.attr#columns}
          attribute's value can be found in the {@link #BlocksLayout} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:columns
        */
        public static final int BlocksLayout_columns = 0;
        /** Attributes that can be used with a TimeRulerView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #TimeRulerView_dividerColor com.tafuta.android.app:dividerColor}</code></td><td></td></tr>
           <tr><td><code>{@link #TimeRulerView_endHour com.tafuta.android.app:endHour}</code></td><td></td></tr>
           <tr><td><code>{@link #TimeRulerView_headerWidth com.tafuta.android.app:headerWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #TimeRulerView_horizontalDivider com.tafuta.android.app:horizontalDivider}</code></td><td></td></tr>
           <tr><td><code>{@link #TimeRulerView_hourHeight com.tafuta.android.app:hourHeight}</code></td><td></td></tr>
           <tr><td><code>{@link #TimeRulerView_labelColor com.tafuta.android.app:labelColor}</code></td><td></td></tr>
           <tr><td><code>{@link #TimeRulerView_labelPaddingLeft com.tafuta.android.app:labelPaddingLeft}</code></td><td></td></tr>
           <tr><td><code>{@link #TimeRulerView_labelTextSize com.tafuta.android.app:labelTextSize}</code></td><td></td></tr>
           <tr><td><code>{@link #TimeRulerView_startHour com.tafuta.android.app:startHour}</code></td><td></td></tr>
           </table>
           @see #TimeRulerView_dividerColor
           @see #TimeRulerView_endHour
           @see #TimeRulerView_headerWidth
           @see #TimeRulerView_horizontalDivider
           @see #TimeRulerView_hourHeight
           @see #TimeRulerView_labelColor
           @see #TimeRulerView_labelPaddingLeft
           @see #TimeRulerView_labelTextSize
           @see #TimeRulerView_startHour
         */
        public static final int[] TimeRulerView = {
            0x7f010001, 0x7f010002, 0x7f010003, 0x7f010004,
            0x7f010005, 0x7f010006, 0x7f010007, 0x7f010008,
            0x7f010009
        };
        /**
          <p>This symbol is the offset where the {@link com.tafuta.android.app.R.attr#dividerColor}
          attribute's value can be found in the {@link #TimeRulerView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:dividerColor
        */
        public static final int TimeRulerView_dividerColor = 6;
        /**
          <p>This symbol is the offset where the {@link com.tafuta.android.app.R.attr#endHour}
          attribute's value can be found in the {@link #TimeRulerView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:endHour
        */
        public static final int TimeRulerView_endHour = 8;
        /**
          <p>This symbol is the offset where the {@link com.tafuta.android.app.R.attr#headerWidth}
          attribute's value can be found in the {@link #TimeRulerView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:headerWidth
        */
        public static final int TimeRulerView_headerWidth = 0;
        /**
          <p>This symbol is the offset where the {@link com.tafuta.android.app.R.attr#horizontalDivider}
          attribute's value can be found in the {@link #TimeRulerView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:horizontalDivider
        */
        public static final int TimeRulerView_horizontalDivider = 2;
        /**
          <p>This symbol is the offset where the {@link com.tafuta.android.app.R.attr#hourHeight}
          attribute's value can be found in the {@link #TimeRulerView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:hourHeight
        */
        public static final int TimeRulerView_hourHeight = 1;
        /**
          <p>This symbol is the offset where the {@link com.tafuta.android.app.R.attr#labelColor}
          attribute's value can be found in the {@link #TimeRulerView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:labelColor
        */
        public static final int TimeRulerView_labelColor = 5;
        /**
          <p>This symbol is the offset where the {@link com.tafuta.android.app.R.attr#labelPaddingLeft}
          attribute's value can be found in the {@link #TimeRulerView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:labelPaddingLeft
        */
        public static final int TimeRulerView_labelPaddingLeft = 4;
        /**
          <p>This symbol is the offset where the {@link com.tafuta.android.app.R.attr#labelTextSize}
          attribute's value can be found in the {@link #TimeRulerView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:labelTextSize
        */
        public static final int TimeRulerView_labelTextSize = 3;
        /**
          <p>This symbol is the offset where the {@link com.tafuta.android.app.R.attr#startHour}
          attribute's value can be found in the {@link #TimeRulerView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:startHour
        */
        public static final int TimeRulerView_startHour = 7;
    };
}
